title: Michael Muraya
email: mkibabu@gmail.com
url: "https://mkibabu.github.io"

exclude: ["README.rst"]
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      meta_description: |
        Software developer based in Raleigh/Durham, North Carolina.
